### PR TITLE
Allow cloning of task descriptions, finitequizzes, and crosswordpuzzles

### LINKED ISSUE #272: Overworld: Improve course cloning
## Current Behavior

Currently only the chickenshock configurations can be cloned.
Currently the descriptions of minigames and npcs can not be cloned.

## Expected Behavior

Chickenshock, bugfinder, crosswordpuzzle and finitequiz configurations are cloned.
The descriptions of minigames and npcs are cloned.

## DoD
- [ ] bugfinder configurations are cloned
- [x] crosswordpuzzle configurations are cloned
- [x] finitequiz configurations are cloned
- [x] descriptions of minigames and npcs are cloned

### PR DESCRIPTION
**Pull request by Aaron2000119**
Closes https://github.com/Gamify-IT/issues/issues/272.
Create a course in the lecturer interface, clone it and check if everything got cloned correctly.

### CODE REVIEW

**Comment by marlau97** [comment]
I tried cloning the PSE course after setting another chickenshock instance and got this error
image

**Review by marlau97 — APPROVED** [review]

**Review by Gr33ndev — APPROVED** [review]

**Comment by delvh** [comment]
Why is the test stuck in a wait loop since the merge?

**Comment by delvh** [comment]
Apart from that, I will merge this PR @ 23:45 if there are no further comments. Test can still be fixed tomorrow.

**Comment by delvh** [comment]
Commit didn't fix the test.

**Comment by Aaron2000119** [comment]
it is fixed locally

**Comment by Aaron2000119** [comment]
and online

**Pull request merged**
