### PR TITLE
Memory included into Overworld Backend

### PR DESCRIPTION
**Pull request by MaximilianWo**
Finished memory for Overworld Backend

### CODE REVIEW

**Comment by maexled** [comment]
Since #59 cloning is not made in the overworld backend anymore. Every minigame backend should provide a clone interface where the minigame backend can clone configurations themselves. Correct me if I am wrong @Aaron2000119

**Comment by MaximilianWo** [comment]
I did it according to this:
https://gamifyit-docs.readthedocs.io/en/latest/dev-manuals/services/integrate-new-minigame.html?highlight=integrate
Did i overlook sth or is it outdated?

**Comment by maexled** [comment]
It's just a new feature we had already planned, which you probably didn't notice.

**Comment by MaximilianWo** [comment]
I added clone Config in the backend. Are the remaining parts good to go?

**Review by PatrickHoltz — APPROVED** [review]

**Review by Aaron2000119 — CHANGES_REQUESTED** [review]
since the cloning is currently chaning, this pr has to be changed as well

**Pull request closed without merging**
